feat: support `prettier-plugin-svelte`
prettier/stylelint-prettier pull request #156
Opened 2021-02-22 13:07 UTC by JounQin

2021-02-22 18:58 UTC, JounQin commented on test/stylelint-prettier-e2e.test.js
> +  test('CSS files', () => {
I don't know why, but the order of the result are reversed sometimes, so I split the two type of files.

https://github.com/prettier/stylelint-prettier/runs/1954057143?check_suite_focus=true#step:7:9

2021-02-28 00:23 UTC, BPScott requested changes
Thanks for the PR!

It does a couple of things unrelated to svelte/angular support, and I've pulled out [avoiding flaky tests](https://github.com/prettier/stylelint-prettier/pull/159) and [testing against prettier v2](https://github.com/prettier/stylelint-prettier/pull/158) into separate PRs.

In light of those changes to help you focus this PR, can you:

- Rebase atop latest master
- Remove the flaky tests fixes as they're already in master
- Remove the prettier v2 ci and the "endOfLine" changes to get that working, as they're already in master (but with a different approach, you shouldn't need to add endOfLine into any prettierrc files)
- Check if renaming the "angular" test fixture file to `check.inert.component.html` will trigger the angular parser and if so, remove the override for "angular.html" files from .prettierrc

2021-02-28 00:23 UTC, BPScott commented on test/prettierrc/custom/.prettierrc
> +    "endOfLine": "auto"
This can be removed, thanks to the more targeted fix in #158

2021-02-28 00:23 UTC, BPScott commented on test/prettierrc/default/.prettierrc
> +  "endOfLine": "auto",
This can be removed, thanks to the more targeted fix in #158

2021-02-28 00:23 UTC, BPScott commented on test/fixtures/check.angular.html
> +<!DOCTYPE html>
https://github.com/prettier/prettier/blob/ce26805e84756953875f30a0c165bd6b09c94ea0/src/language-html/index.js#L13 suggests that you can trigger the angular parser by using the `.component.html` extension. 

If we name this file `check.inert.component.html` then it looks like we should trigger using the angular component without needing to add any of the overrides in our base prettierrc.

2021-02-28 00:23 UTC, BPScott commented on .prettierrc
> +  "overrides": [
By naming our fixture file `check.inert.component.html` we should be able to trigger the angular parser without needing to add this custom override. Can you confirm if that works and if so rename the fixture file and remove this?

2021-02-28 01:13 UTC, BPScott commented
As I was feeling on a roll I've addressed my concerns in #160 rather than making you do it all.

I've published stylelint-prettier 1.2.0 with support for the angular and svelte parsers.

I'm going to close this PR as I think the root cause has been addressed. If you're still having issues please reopen with a set of changes against latest master.

2021-02-28 01:13 UTC, closed without merging